spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spreezy
    username: dummy_owner
    password: dummy@123
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:db/changelog/restaurant-master-changelog.xml
    enabled: true
    drop-first: false
    default-schema: dummy