server:
  port: 8081

spring:
  application:
    name: DEV application
  datasource:
    url: jdbc:postgresql://localhost:5432/spreezy
    username: spreezy
    password: spreezy@123
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
